# Generated by Django 5.0.6 on 2024-06-12 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_app', models.CharField(max_length=20)),
                ('imei', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InformacaoCTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_md_fe', models.CharField(max_length=12)),
                ('ch_cte', models.CharField(max_length=12)),
                ('dh_chegada', models.DateTimeField()),
                ('dh_reg_sistema', models.DateTimeField()),
                ('cod_ocorrencia', models.CharField(max_length=2)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inf_cte', to='dispositivos.dispositivo')),
            ],
        ),
    ]
